version: '3.8'

services:
  wordpress:
    image: wordpress:6.5-php8.2-apache
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_HOST: ${DB_HOST}
