version: '3.8'
services:
  db-init:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - ./dump.sql:/dump.sql:ro
    command: >
      sh -c '
        echo "Creating database and user..." &&
        mysql -h "${DB_HOST}" -u root -prootpassword -e "
          CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`;
          CREATE USER IF NOT EXISTS '\''${DB_USER}'\''@'\''%'\'' IDENTIFIED BY '\''${DB_PASSWORD}'\'';
          GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '\''${DB_USER}'\''@'\''%'\''; 
          FLUSH PRIVILEGES;
        " &&
        if [ -f /dump.sql ]; then
          echo "Importing dump.sql..." &&
          cat /dump.sql | mysql -h "${DB_HOST}" -u "${DB_USER}" -p"${DB_PASSWORD}" "${DB_NAME}"
        else
          echo "No dump.sql found, skipping import."
        fi
      '

    network_mode: host
    restart: 'no'
