name: MySQL
services:
  db:
    container_name: db-server
    image: mysql:latest
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin:latest
    restart: no
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
