version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    restart: 'no'
